directory:
  - .
quiet: true
soft-fail: false
framework:
  - terraform
output:
  - cli
  - junitxml
download-external-modules: true
evaluate-variables: true
skip-check:
  - CKV2_AWS_28  # WAF association for ALB - deferred to prod (E09/E10)
