formatter: "markdown table"

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: infra/modules

sections:
  show:
    - header
    - usage
    - inputs
    - outputs
    - providers
    - resources

content: |-
  {{ .Header }}

  ## Usage
  ```hcl
  {{ .Usage }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}
