name: "Terraform CI"

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.tf'
      - '.github/workflows/terraform-ci.yml'
  push:
    branches: [ main ]
    paths:
      - '**/*.tf'

# Explicitly set minimal permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pull-requests: read

jobs:
  terraform:
    name: "Terraform Quality Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive infra/

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.0

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: |
          cd infra
          tflint -f compact

      - name: Run  Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          quiet: true
          framework: terraform
          output_format: cli
